### ISSUE TITLE
Generic building

### ISSUE THREAD

**Issue by spel-oe** [F5OEO/kisspectrum#1]
Hello,
a small generic spectrum and waterfall tool would be nice for other devices as well.
Is there any possibility to build this project without running into Raspberry-dependencies?
like "bcm_host.h" or unknown type name ‘DISPMANX_ELEMENT_HANDLE_T‘

regards
spel-oe

**Comment by F5OEO** [comment]
Unfortunatelly this use OpenVG and DispManx for graphic acceleration...so very specific to Raspberry pi.

**Comment by spel-oe** [comment]
thanks for the quick reply
